# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20151229_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email_addr',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
