# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20151231_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='RegistrationProfile',
        ),
    ]
